### ISSUE TITLE
 401 UNAUTHORIZED

### ISSUE THREAD

**Issue by jnordling** [onaio/onapie#29]
I know my username and password, and I always get the following error.

Are there any server side configuration i need to do like enable cores?

 Just wanted to let you know. 

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/onapie/client.py", line 24, in __init__
    self.authenticate(username, password)
  File "/Library/Python/2.7/site-packages/onapie/client.py", line 45, in authenticate
    username, password)).text).get('api_token')
  File "/Library/Python/2.7/site-packages/onapie/utils.py", line 62, in get
    return self.request('GET', path, None, None, headers, **extras)
  File "/Library/Python/2.7/site-packages/onapie/utils.py", line 54, in request
    raise ClientException(None, self.last_response)
onapie.exceptions.ClientException: 401, UNAUTHORIZED

**Comment by jnordling** [comment]
I found the issue. Commit #28 actually broke it. I will fix it and add a pull request.
