### ISSUE TITLE
Throws ImportError in Python 2.7

### ISSUE THREAD

**Issue by KaitCrawford** [onaio/onapie#36]
When trying to import this module in Python 2.7 the following error is seen:
```
>>> from onapie.client import Client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaitlyn/VMachines/malaria24-django/ve/src/onapie/onapie/client.py", line 7, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse
```

I've already created a PR to fix this here https://github.com/onaio/onapie/pull/35

**Comment by ukanga** [comment]
closed by #35
